repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
